### Mitarbeiter als Einstiegspunkt
PUT {{lohnsoftware}}/api/Carol/arbeitsstunden/2024/7/
Content-Type: application/json

{
  "stunden": 40,
  "minuten": 2
}

### Erfasse Arbeitsstunden
# Zeitraum als Einstiegsunkt
# Aus der Perspektive des Geschäftsführers der die Abreitsstunden für sein Mitarbeiter monatlich erfasst
# sieht der resource identifier für mich sinnvoller aus
# @no-cookie-jar
PUT {{lohnsoftware}}/api/arbeitsstunden/2024/7/Carol
Authorization: Basic {{BasicAuthAlice}}
Content-Type: application/json

{
  "stunden": 40,
  "minuten": 2
}
